# Generated by Django 3.1.4 on 2021-02-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pictureID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Image.picture'),
            preserve_default=False,
        ),
    ]
