# Generated by Django 3.1.4 on 2021-01-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diningHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=50)),
                ('tableNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='diningHallReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('hallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diningHall.dininghall')),
                ('mealID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
