# Generated by Django 3.1.4 on 2021-02-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reserved'),
        ('diningHall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghallreservation',
            name='reservedID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.reserved'),
            preserve_default=False,
        ),
    ]
