# Generated by Django 3.1.4 on 2021-02-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventreservation_reservedid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreservation',
            name='reservedID',
        ),
    ]
