# Generated by Django 3.1.4 on 2021-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(null=True, upload_to='')),
                ('photo2', models.ImageField(null=True, upload_to='')),
                ('photo3', models.ImageField(null=True, upload_to='')),
                ('photo4', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
