# Generated by Django 3.1.4 on 2021-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='photo',
        ),
        migrations.AddField(
            model_name='picture',
            name='photo1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='photo2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='photo3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='photo4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
