# Generated by Django 3.1.4 on 2021-01-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diningHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=50)),
                ('tableNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='mealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typenName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountPercent', models.IntegerField()),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('tsCreated', models.DateTimeField(editable=False)),
                ('tsUpdated', models.DateTimeField()),
                ('guestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.guest')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('discountPercent', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='roomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.reservation')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.roomtype'),
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.mealtype')),
            ],
        ),
        migrations.CreateModel(
            name='guestInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceAmount', models.IntegerField()),
                ('tsIssued', models.DateTimeField(editable=False)),
                ('tsPaid', models.DateTimeField()),
                ('guestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.guest')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='eventReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfGuest', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('purposeDescribe', models.CharField(max_length=500)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.event')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='diningHallReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('hallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.dininghall')),
                ('mealID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.meal')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.reservation')),
            ],
        ),
    ]
