# Generated by Django 3.1.4 on 2021-01-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='discountPercent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='discountPercent',
        ),
    ]
