# Generated by Django 3.1.4 on 2021-01-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20210128_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dininghallreservation',
            name='hallID',
        ),
        migrations.RemoveField(
            model_name='dininghallreservation',
            name='mealID',
        ),
        migrations.RemoveField(
            model_name='dininghallreservation',
            name='reservationID',
        ),
        migrations.RemoveField(
            model_name='eventreservation',
            name='eventID',
        ),
        migrations.RemoveField(
            model_name='eventreservation',
            name='reservationID',
        ),
        migrations.RemoveField(
            model_name='guestinvoice',
            name='guestID',
        ),
        migrations.RemoveField(
            model_name='guestinvoice',
            name='reservationID',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guestID',
        ),
        migrations.RemoveField(
            model_name='room',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='reservationID',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='roomID',
        ),
        migrations.DeleteModel(
            name='diningHall',
        ),
        migrations.DeleteModel(
            name='diningHallReservation',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='eventReservation',
        ),
        migrations.DeleteModel(
            name='guest',
        ),
        migrations.DeleteModel(
            name='guestInvoice',
        ),
        migrations.DeleteModel(
            name='meal',
        ),
        migrations.DeleteModel(
            name='mealType',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.DeleteModel(
            name='room',
        ),
        migrations.DeleteModel(
            name='roomReservation',
        ),
        migrations.DeleteModel(
            name='roomType',
        ),
    ]
